import { SQUARE } from '@/utils/constant'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Đổi mới sáng tạo',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${SQUARE.className} antialiased`}>{children}</body>
    </html>
  )
}
