import { AppProvider } from '@/redux/providers/AppProvider'
import { SQUARE } from '@/utils/constant'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Đổi mới sáng tạo',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <AppProvider>
      <html lang="en" suppressHydrationWarning>
        <meta
          http-equiv="Content-Security-Policy"
          content="upgrade-insecure-requests"></meta>
        <body className={`${SQUARE.className} antialiased`}>{children}</body>
      </html>
    </AppProvider>
  )
}
